#!/usr/bin/env bash

cd $(realpath $(dirname -- $0))

set -- \
    "project.org" \
    "installed.org" \
    ".bashrc" \
    ".bash_aliases" \
    ".gemrc" \
    ".gitconfig" \
    ".emacs.d/init.el" \
    ".emacs.d/early-init.el" \
    ".emacs.d/KEYBINDING.org" \
    ".emacs.d/init-lisp/" \
    ".emacs.d/tool-lisp/" \
    ".emacs.d/snippets/" \
    "bin/" \

for v in "$@"; do
    if [ ! -e "$v" ]; then
        echo "error: '$PWD/$v' does not exist"
        return 1
    fi

    if [ -d "$v" ]; then
        if [ ! -e "$HOME/$v" ]; then
            mkdir -p "$HOME/$v" || echo "error: unable to make dir '$HOME/$v'"; return 1
        fi

        for v2 in "$v"*; do
            if [ -f "$v2" ]; then
                suf="$(echo -n $v2 | tail -c 1)"
                # Ignore backup files; prefix ’#’ or suffix ’~’
                if [ suf = "#" ] || [ suf = "~" ]; then
                    continue
                fi

                ./bin/link_file "$PWD/$v2" "$HOME/$v2"
            fi
        done

    else
        if [ ! -e "$HOME/$(dirname $v)" ]; then
            mkdir -p "$HOME/$(dirname $v)" || echo "error: unable to make dir '$HOME/$(dirname $v)'"; return 1
        fi

        ./bin/link_file "$PWD/$v" "$HOME/$v"
    fi
done
